### ISSUE TITLE
Add example of using pagination in "list products" method docs

### ISSUE THREAD

**Issue by robbieaverill** [chec/commerce.js#135] opened 2021-02-23 18:52 UTC
https://commercejs.com/docs/sdk/products#list-products

Would be nice to show a short example of how to adjust the page length and page number using `commerce.products.list()`, since it seems to trip devs up occasionally.

**Comment by eufandem** [comment] 2021-02-23 19:59
Video content idea right there.

**Comment by jaepass** [comment] 2021-04-07 23:06
Duplicate of https://github.com/chec/commerce.js/issues/121

**Closed by jaepass** 2021-04-07 23:06 UTC
Labels: enhancement
